# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HOcOnlineACT' do
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'
  	pod 'Firebase/Messaging'

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HOcOnlineACT

  target 'HOcOnlineACT-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HOcOnlineACTTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

